version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip3 install mysql-connector-python -t .
      - zip bundle.zip *
      - aws lambda update-function-code --function-name macdas --zip-file fileb://bundle.zip