version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip3 install mysql-connector-python bybit importlib-metadata pytelegrambotapi -t .
      - |
        chmod 644 $(find . -type f)
        chmod 755 $(find . -type d)
      - zip -r bundle.zip *
      - aws lambda update-function-code --function-name macdas --zip-file fileb://bundle.zip --region eu-west-2
      - aws lambda update-function-code --function-name macdas --zip-file fileb://bundle.zip --region us-east-1